### ISSUE TITLE
Release to ROS hydro?

### ISSUE THREAD

**Issue by abencz** [ros-visualization/interactive_marker_proxy#1]
Hi David,

I noticed this package is used in the [ros3djs](http://wiki.ros.org/ros3djs/Tutorials/VisualizingInteractiveMarkers) tutorial. Are there any plans to release it to Hydro or does the tutorial need to be changed for the Hydro version of ROS?

**Comment by clalancette** [comment]
Closing this out since we are archiving this repository.
